### ISSUE TITLE
请问，如果我只用 feign 和 okhttp 相关的怎么弄啊？

### ISSUE THREAD

**Issue by yjph83** [Rpbht/spring-boot-feign#1]
我去掉 注册中心后，会报这个启动错误，
javax.management.InstanceNotFoundException: org.springframework.boot:type=Admin,name=SpringApplication
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.8.0_111]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643) ~[na:1.8.0_111]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) ~[na:1.8.0_111]

这个错误，启动要报， 但是不影响运行，不过可以通过idea配置，不现实错误，但是不是最终的解决办法！ 请教下这个如何应用啊？ 谢谢！

**Comment by yjph83** [comment]
也就是说我在  client 项目中，我只用feign ，不能包含eureka 的任何东西，兄弟请教下嘛，我这边始终要报这个错误！~谢谢！
